# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Fabrikk < Formula
  desc "Spec-driven autonomous run system for coding agents"
  homepage "https://github.com/php-workx/fabrikk"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/php-workx/fabrikk/releases/download/v0.1.0/fabrikk_0.1.0_darwin_amd64.tar.gz"
      sha256 "70316a9aae6e3d8ef8334bdd39c3402a7dace95a9800daa0d6a363b8097f976f"

      define_method(:install) do
        bin.install "fabrikk"
        bin.install_symlink "fabrikk" => "fab"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/php-workx/fabrikk/releases/download/v0.1.0/fabrikk_0.1.0_darwin_arm64.tar.gz"
      sha256 "ba0dee39acb5b4172501881b25c0b3168860b9a4fc479b360eb77e2a5079cd87"

      define_method(:install) do
        bin.install "fabrikk"
        bin.install_symlink "fabrikk" => "fab"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/php-workx/fabrikk/releases/download/v0.1.0/fabrikk_0.1.0_linux_amd64.tar.gz"
      sha256 "c295b36e044a2bed129b9857282d74b3a3c39c14835327924e1a68809f616b60"
      define_method(:install) do
        bin.install "fabrikk"
        bin.install_symlink "fabrikk" => "fab"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/php-workx/fabrikk/releases/download/v0.1.0/fabrikk_0.1.0_linux_arm64.tar.gz"
      sha256 "28c2556e6a5691287eb3a71c52402ca5f69e9684c563228986e86fcd7cda452f"
      define_method(:install) do
        bin.install "fabrikk"
        bin.install_symlink "fabrikk" => "fab"
      end
    end
  end

  test do
    system "#{bin}/fabrikk", "--version"
  end
end
