# This file was generated by GoReleaser. DO NOT EDIT.
cask "epos" do
  version "0.2.3"

  on_macos do
    on_intel do
      sha256 "c36879e460bcee63b182cfe4913ebcae6079f88f4f6f346d585e74175d22acab"
      url "https://github.com/php-workx/epos/releases/download/v#{version}/epos_#{version}_Darwin_x86_64.tar.gz",
        verified: "github.com/php-workx/epos"
    end
    on_arm do
      sha256 "39a8d693587d24517d758a56c715024a410f54f44ffcc32b03d548a6a61ffe1c"
      url "https://github.com/php-workx/epos/releases/download/v#{version}/epos_#{version}_Darwin_arm64.tar.gz",
        verified: "github.com/php-workx/epos"
    end
  end

  on_linux do
    on_intel do
      sha256 "8a3b667ebeafe554d7938efb1bad569f98be713c427b34f7197eb106eaa363ca"
      url "https://github.com/php-workx/epos/releases/download/v#{version}/epos_#{version}_Linux_x86_64.tar.gz",
        verified: "github.com/php-workx/epos"
    end
    on_arm do
      sha256 "0c01dfeb2725aada8312b1fa5f18a5a14baba91f25dc91152305fd57aeb371a0"
      url "https://github.com/php-workx/epos/releases/download/v#{version}/epos_#{version}_Linux_arm64.tar.gz",
        verified: "github.com/php-workx/epos"
    end
  end

  name "epos"
  desc "A task and issue tracker for AI agents and their humans"
  homepage "https://github.com/php-workx/epos"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "epos"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/epos"]
    end
  end

  # No zap stanza required

end
