# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Fuse < Formula
  desc "A local firewall for AI agent commands"
  homepage "https://github.com/php-workx/fuse"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/php-workx/fuse/releases/download/v0.1.0/fuse_darwin_amd64.tar.gz"
      sha256 "b90eb5db97ea9ec5673af2ea4ba8f48f877ee0ad19e89cc731204ea9bca61e36"

      define_method(:install) do
        bin.install "fuse"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/php-workx/fuse/releases/download/v0.1.0/fuse_darwin_arm64.tar.gz"
      sha256 "3994c09cd7f6a75c877a689a835745a3299c845942a14120443c4b2b6229ed87"

      define_method(:install) do
        bin.install "fuse"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/php-workx/fuse/releases/download/v0.1.0/fuse_linux_amd64.tar.gz"
      sha256 "8fb7bc20c597bcb395cf459896aa0ccb5d2a819da1e723d7b2ffbbdb70e0e701"
      define_method(:install) do
        bin.install "fuse"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/php-workx/fuse/releases/download/v0.1.0/fuse_linux_arm64.tar.gz"
      sha256 "ef00b8a046ddac6663584b183d45f37e31217853cc3385dd022af5edbe733e66"
      define_method(:install) do
        bin.install "fuse"
      end
    end
  end

  test do
    system "#{bin}/fuse", "--help"
  end
end
