# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Fuse < Formula
  desc "A local firewall for AI agent commands"
  homepage "https://github.com/php-workx/fuse"
  version "0.1.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/php-workx/fuse/releases/download/v0.1.2/fuse_darwin_amd64.tar.gz"
      sha256 "f7814d696cec10ab898908f72d2fff2848332e43c387e004e39f3a90d9c916a1"

      define_method(:install) do
        bin.install "fuse"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/php-workx/fuse/releases/download/v0.1.2/fuse_darwin_arm64.tar.gz"
      sha256 "16584ac9eecc0d8e434a03daa4790b030122a2db66b30ec6a392becbacacca0c"

      define_method(:install) do
        bin.install "fuse"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/php-workx/fuse/releases/download/v0.1.2/fuse_linux_amd64.tar.gz"
      sha256 "e628dd46f4e5a242ee1b7d1268903ba563154fdfee491df656b93e1914b52ee7"
      define_method(:install) do
        bin.install "fuse"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/php-workx/fuse/releases/download/v0.1.2/fuse_linux_arm64.tar.gz"
      sha256 "b75ed841f6d87725e900f4f5317fb6114f28783d3486044f60e3ddcc75409001"
      define_method(:install) do
        bin.install "fuse"
      end
    end
  end

  test do
    system "#{bin}/fuse", "--help"
  end
end
