# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Fuse < Formula
  desc "A local firewall for AI agent commands"
  homepage "https://github.com/php-workx/fuse"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/php-workx/fuse/releases/download/v0.1.1/fuse_darwin_amd64.tar.gz"
      sha256 "eeec0236248b24920a30b988b08fbbdd25f31a254f2ecf340b88008abb2e4363"

      define_method(:install) do
        bin.install "fuse"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/php-workx/fuse/releases/download/v0.1.1/fuse_darwin_arm64.tar.gz"
      sha256 "c5d3e77e56892ef5f2de2358c79618d9bc84693d35ca52718ef46e602d9f9eee"

      define_method(:install) do
        bin.install "fuse"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/php-workx/fuse/releases/download/v0.1.1/fuse_linux_amd64.tar.gz"
      sha256 "32e07844732561a28324b63044cc2566e62865105a2633247c9b8b7d589243da"
      define_method(:install) do
        bin.install "fuse"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/php-workx/fuse/releases/download/v0.1.1/fuse_linux_arm64.tar.gz"
      sha256 "9b8693838a98b986c768ff495c309930f8c311c5bc46e45ebb961ecf1936a64c"
      define_method(:install) do
        bin.install "fuse"
      end
    end
  end

  test do
    system "#{bin}/fuse", "--help"
  end
end
